export enum UserRole {
  ADMIN = 'ADMIN',
  ORGANIZER = 'ORGANIZER',
  PARTICIPANT = 'PARTICIPANT',
  USER = 'USER',
}

export enum TournamentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TournamentLevel {
  LEVEL_I = 'I',
  LEVEL_II = 'II',
  LEVEL_III = 'III',
}

export enum RegistrationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum NotificationType {
  REGISTRATION_CONFIRMATION = 'REGISTRATION_CONFIRMATION',
  REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
  TOURNAMENT_PUBLISHED = 'TOURNAMENT_PUBLISHED',
  TOURNAMENT_CANCELLED = 'TOURNAMENT_CANCELLED',
  TOURNAMENT_UPDATE = 'TOURNAMENT_UPDATE',
  GROUP_DRAW = 'GROUP_DRAW',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  NEW_TOURNAMENT_MATCH = 'NEW_TOURNAMENT_MATCH',
  SYSTEM = 'SYSTEM',
}

export enum Currency {
  EUR = 'EUR',
  RON = 'RON',
  USD = 'USD',
  GBP = 'GBP',
}

export enum AgeCategory {
  U5 = 'U5',
  U6 = 'U6',
  U7 = 'U7',
  U8 = 'U8',
  U9 = 'U9',
  U10 = 'U10',
  U11 = 'U11',
  U12 = 'U12',
  U13 = 'U13',
  U14 = 'U14',
  U15 = 'U15',
  U16 = 'U16',
  U17 = 'U17',
  U18 = 'U18',
  U19 = 'U19',
  U20 = 'U20',
  U21 = 'U21',
  U22 = 'U22',
  U23 = 'U23',
  SENIOR = 'SENIOR',
  VETERANS = 'VETERANS',
}

export enum TournamentFormat {
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
  DOUBLE_ELIMINATION = 'DOUBLE_ELIMINATION',
  ROUND_ROBIN = 'ROUND_ROBIN',
  GROUPS_PLUS_KNOCKOUT = 'GROUPS_PLUS_KNOCKOUT',
  LEAGUE = 'LEAGUE',
}

export enum Language {
  EN = 'EN',
  RO = 'RO',
}
